---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: 🤞 Manual Build


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Dispatch: allows for manual trigger via GH UI
  workflow_dispatch:
    inputs:
      run-name:
        description: 'Name of workflow'
        required: true
        default: '🤞 Manual Build'
        type: string
      version:
        description: 'Comma separated list of version (example: "8.0", "8.1")'
        required: true
        default: '"8.3"'
        type: string
      arch:
        description: 'Comma separated list of Arch platform (example: "linux/amd64", "linux/arm64")'
        required: true
        default: '"linux/amd64", "linux/arm64"'
        type: string
      default_branch:
        description: 'The default branch of this repository to fetch latest tags from. Default: my-image'
        required: false
        default: 'my-image'
        type: string
      tag:
        description: 'The name for the "latest" Docker tag (default: latest).'
        required: false
        default: 'latest'
        type: string
      branches:
        description: 'Comma separated list of branches to create build matrix for. Default: my-image'
        required: false
        default: 'my-image'
        type: string
      enabled:
        description: 'Enable'
        type: boolean
        required: true
        default: true
      deploy:
        description: 'Deploy image'
        type: boolean
        required: true
        default: false


# -------------------------------------------------------------------------------------------------
# Custom Variables
# -------------------------------------------------------------------------------------------------
env:
  VERSIONS: >-
    [
      {
        "NAME":    "PHP",
        "VERSION": ${{ format('[{0}]', inputs.version) }},
        "FLAVOUR": ["default"],
        "ARCH":    ${{ format('[{0}]', inputs.arch) }}
      }
    ]
  REFS: >
    {
        "DEFAULT_BRANCH": ${{ format('"{0}"', inputs.default_branch) }},
        "BRANCHES": ${{ format('"{0}"', inputs.branches) }},
        "NUM_LATEST_TAGS": 0
    }

# -------------------------------------------------------------------------------------------------
# Custom name of workflow
# -------------------------------------------------------------------------------------------------
run-name: ${{ inputs.run-name }} 🚀


jobs:
  # (1/10) Determine env
  set-env:
    name: Compute env
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ env.VERSIONS }}
      refs: ${{ env.REFS }}
#      versions: ${{ steps.variables.outputs.versions }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: variables
        if: false
        run: echo
#        run: |
#          echo "versions=${{ env.VERSIONS }}" >> $GITHUB_OUTPUT
  # -----------------------------------------------------------------------------------------------
  # (1/9) Determine parameter settings
  # -----------------------------------------------------------------------------------------------
  params:
    name: Compute params
    needs: [set-env]
    uses: ./.github/workflows/params.yml
    with:
      versions: ${{ needs.set-env.outputs.versions }}
      refs: ${{ needs.set-env.outputs.refs }}


  # -----------------------------------------------------------------------------------------------
  # (2/9) Configure Build and Deploy Matrices
  # -----------------------------------------------------------------------------------------------
  configure:
    needs: [params]
    uses: ./.github/workflows/docker-multistage-configure.yml
    with:
      enabled: ${{ inputs.enabled }}
      can_deploy: ${{ inputs.deploy }}
      versions: ${{ needs.params.outputs.versions }}
      refs: ${{ needs.params.outputs.refs }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}


  # -----------------------------------------------------------------------------------------------
  # (3/9) Build & Test base
  # -----------------------------------------------------------------------------------------------
  build-base:
    needs:
      - configure
    uses: ./.github/workflows/docker-multistage-build.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      pull_base_image: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: base
      stage_prev: ''
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}

  test-base:
    needs:
      - configure
      - build-base
    uses: ./.github/workflows/docker-multistage-test.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: base


  # -----------------------------------------------------------------------------------------------
  # (4/9) Build & Test mods
  # -----------------------------------------------------------------------------------------------
  build-mods:
    needs:
      - configure
      - build-base
    uses: ./.github/workflows/docker-multistage-build.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: mods
      stage_prev: base
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}

  test-mods:
    needs:
      - configure
      - build-mods
    uses: ./.github/workflows/docker-multistage-test.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: mods


  # -----------------------------------------------------------------------------------------------
  # (5/9) Build & Test prod
  # -----------------------------------------------------------------------------------------------
  build-prod:
    needs:
      - configure
      - build-mods
    uses: ./.github/workflows/docker-multistage-build.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: prod
      stage_prev: mods
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}

  test-prod:
    needs:
      - configure
      - build-prod
    uses: ./.github/workflows/docker-multistage-test.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: prod


  # -----------------------------------------------------------------------------------------------
  # (6/9) Build & Test slim
  # -----------------------------------------------------------------------------------------------
  build-slim:
    needs:
      - configure
      - build-prod
    uses: ./.github/workflows/docker-multistage-build.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: slim
      stage_prev: prod
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}

  test-slim:
    needs:
      - configure
      - build-slim
    uses: ./.github/workflows/docker-multistage-test.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: slim


  # -----------------------------------------------------------------------------------------------
  # (7/9) Build & Test work
  # -----------------------------------------------------------------------------------------------
  build-work:
    needs:
      - configure
      - build-slim
    uses: ./.github/workflows/docker-multistage-build.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      run_tests: false
      upload_artifact: true
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: work
      stage_prev: slim
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}

  test-work:
    needs:
      - configure
      - build-work
    uses: ./.github/workflows/docker-multistage-test.yml
    with:
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: work


  # -----------------------------------------------------------------------------------------------
  # (8/9) Push images
  # -----------------------------------------------------------------------------------------------
  push-base:
    needs:
      - configure
      - test-base
      - test-mods
      - test-prod
      - test-slim
      - test-work
    uses: ./.github/workflows/docker-multistage-push-image.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: base
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  push-mods:
    needs:
      - configure
      - test-base
      - test-mods
      - test-prod
      - test-slim
      - test-work
    uses: ./.github/workflows/docker-multistage-push-image.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: mods
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  push-prod:
    needs:
      - configure
      - test-base
      - test-mods
      - test-prod
      - test-slim
      - test-work
    uses: ./.github/workflows/docker-multistage-push-image.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: prod
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  push-slim:
    needs:
      - configure
      - test-base
      - test-mods
      - test-prod
      - test-slim
      - test-work
    uses: ./.github/workflows/docker-multistage-push-image.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: slim
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  push-work:
    needs:
      - configure
      - test-base
      - test-mods
      - test-prod
      - test-slim
      - test-work
    uses: ./.github/workflows/docker-multistage-push-image.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_build }}
      artifact_prefix: ${{ needs.configure.outputs.artifact_prefix }}
      stage: work
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}


  # -----------------------------------------------------------------------------------------------
  # (9/9) Push Manifests
  # -----------------------------------------------------------------------------------------------
  manifest-base:
    needs:
      - configure
      - push-base
    uses: ./.github/workflows/docker-multistage-push-manifest.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: base
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  manifest-mods:
    needs:
      - configure
      - push-mods
    uses: ./.github/workflows/docker-multistage-push-manifest.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: mods
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  manifest-prod:
    needs:
      - configure
      - push-prod
    uses: ./.github/workflows/docker-multistage-push-manifest.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: prod
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  manifest-slim:
    needs:
      - configure
      - push-slim
    uses: ./.github/workflows/docker-multistage-push-manifest.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: slim
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  manifest-work:
    needs:
      - configure
      - push-work
    uses: ./.github/workflows/docker-multistage-push-manifest.yml
    with:
      can_deploy: ${{ needs.configure.outputs.can_login == 'true' && needs.configure.outputs.can_push == 'true' }}
      has_refs: ${{ needs.configure.outputs.has_refs == 'true' }}
      matrix: ${{ needs.configure.outputs.matrix_deploy }}
      versions: ${{ needs.configure.outputs.versions }}
      stage: work
      default_branch: ${{ inputs.default_branch }}
      tag: ${{ inputs.tag }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
